baseURL = 'https://plancky.github.io/shashvat.dev'
languageCode = 'en-us'
title = "Shashvat.dev"

[markup.goldmark.renderer]
unsafe = true

############################# Modules ############################
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[build.cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[build.cachebusters]]
source = 'data/.*\.(.*)$'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

# CSS Plugins
# [[params.plugins.css]]
# link = "plugins/swiper/swiper-bundle.css"
# lazy = true
# [[params.plugins.css]]
# link = "plugins/glightbox/glightbox.css"
# lazy = true
# [[params.plugins.css]]
# link = "plugins/font-awesome/v6/brands.css"
# lazy = true
# [[params.plugins.css]]
# link = "plugins/font-awesome/v6/solid.css"
# lazy = true
# [[params.plugins.css]]
# link = "plugins/font-awesome/v6/icons.css"
# lazy = true