# Other Configuration 
katex = true

# Author Info
[author]
    name="Shashvat Jain"
    email="shashvat817@gmail.com"

[heading]
main="Shash"

[connect]
links = ["email: shashvat817@gmail.com", "x: @planck0"]
mail="shashvat817@gmail.com"
twitter="@planck0"

